export const SURVEY_CHANGE_NAME = 'SURVEY_CHANGE_NAME';
export const SURVEY_CHANGE_DESCRIPTION = 'SURVEY_CHANGE_DESCRIPTION';
export const SURVEY_SAVE = 'SURVEY_SAVE';
export const QUESTION_ADD_NEW = 'QUESTION_ADD_NEW';
export const QUESTION_CHANGE_TITLE = 'QUESTION_CHANGE_TITLE';
export const QUESTION_CHANGE_TYPE = 'QUESTION_CHANGE_TYPE';
export const ANSWER_OPTION_ADD_NEW = 'ANSWER_OPTION_ADD_NEW';
export const ANSWER_OPTION_CHANGE_TITLE = 'ANSWER_OPTION_CHANGE_TITLE';
