export const AUTH_SIGN_IN_SUCCESS = 'AUTH_SIGN_IN_SUCCESS';
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const AUTH_SIGN_OUT_SUCCESS = 'AUTH_SIGN_OUT_SUCCESS';

export const SURVEY_UPDATE = 'SURVEY_UPDATE';

export const SURVEY_SAVE_ANSWERS = 'SURVEY_SAVE_ANSWERS';
export const SURVEY_SAVE = 'SURVEY_SAVE';
export const SURVEY_INIT_NEW = 'SURVEY_INIT_NEW';
export const SURVEY_CLEAN_UP = 'SURVEY_CLEAN_UP';

export const QUESTION_ADD_NEW = 'QUESTION_ADD_NEW';
export const QUESTION_CHANGE_TYPE = 'QUESTION_CHANGE_TYPE';
export const QUESTION_DELETE = 'QUESTION_DELETE';

export const ANSWER_OPTION_ADD_NEW = 'ANSWER_OPTION_ADD_NEW';
export const ANSWER_OPTION_CHANGE_TITLE = 'ANSWER_OPTION_CHANGE_TITLE';

