export const SURVEY_CHANGE_NAME = 'SURVEY_CHANGE_NAME';
export const SURVEY_LOAD_SUCCESS = 'SURVEY_LOAD_SUCCESS';
export const SURVEY_CHANGE_DESCRIPTION = 'SURVEY_CHANGE_DESCRIPTION';
export const SURVEY_SAVE_ANSWERS = 'SURVEY_SAVE_ANSWERS';
export const SURVEY_SAVE = 'SURVEY_SAVE';

export const QUESTION_ADD_NEW = 'QUESTION_ADD_NEW';
export const QUESTION_CHANGE_TITLE = 'QUESTION_CHANGE_TITLE';
export const QUESTION_CHANGE_TYPE = 'QUESTION_CHANGE_TYPE';
export const QUESTION_DELETE_QUESTION = 'QUESTION_DELETE_QUESTION';

export const ANSWER_OPTION_ADD_NEW = 'ANSWER_OPTION_ADD_NEW';
export const ANSWER_OPTION_CHANGE_TITLE = 'ANSWER_OPTION_CHANGE_TITLE';

export const SURVEY_FORM_INIT_FORM_CONFIG = 'SURVEY_FORM_INIT_FORM_CONFIG';
export const SURVEY_FORM_CHANGE_QUESTION_ANSWER = 'SURVEY_FORM_CHANGE_QUESTION_ANSWER';
